# Generated by Django 4.2.7 on 2025-05-30 22:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenerationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('generation_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fuel_type', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity_mw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IEXData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('load_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('block_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mcp', models.DecimalField(decimal_places=2, help_text='Market Clearing Price', max_digits=10)),
                ('mcv', models.DecimalField(decimal_places=2, help_text='Market Clearing Volume', max_digits=15)),
                ('purchase_bid_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sell_bid_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'ordering': ['-timestamp', 'block_number'],
                'unique_together': {('product', 'timestamp', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='LoadSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('block_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_drawal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_drawal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discom')),
            ],
            options={
                'ordering': ['-date', 'block_number'],
                'unique_together': {('discom', 'date', 'block_number')},
            },
        ),
        migrations.CreateModel(
            name='GenerationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('block_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_generation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('actual_generation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generator')),
            ],
            options={
                'ordering': ['-date', 'block_number'],
                'unique_together': {('generator', 'date', 'block_number')},
            },
        ),
    ]
